site_name: SKT TKS
repo_name: openinfradev/tks-service-info
repo_url: https://github.com/openinfradev/tks-service-info
theme:
  language: kr
  name: material
  logo: assets/taco_icon.png
  font:
    text: Noto Sans Korean  
  palette: 
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
   - scheme: slate 
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate       
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  highlightjs: true

plugins:
  - search
#  - awesome-pages
#  - section-index
#  - mike:
#      # these fields are all optional; the defaults are as below...
#      version_selector: true   # set to false to leave out the version selector
#      css_dir: css             # the directory to put the version selector's CSS
#      javascript_dir: js       # the directory to put the version selector's JS

extra_css:
    - assets/css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#    - emoji_index: !!python/name:materialx.emoji.twemoji
#    - emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - 소개: index.md
  - 자습서: selfstudy/tks-selfstudy.md
  - Architecture: 
      - 'Overview': architecture/overviewarch.md
      - 'AWS Ref. Architecture': architecture/awsarch.md
